# Exploratory Data Analysis

As of Milestone 2, we have written logic for importing and cleaning the datasets we will use later on our models. This notebook will immediately follow that and take a look at what is actually in these files and what other information we can extract from them. We'll use Pandas to help visualize data.

In [8]:
import numpy as np
import pandas as pd

# import and load config variables
from vgc_matchup_predictor.utils.config import load_config 
config = load_config()

If you are following this notebook in a cloned repository and the third line raises an error for you, you likely have not set up the repository as a package yet. This is an easy fix; after cloning the repository, generate a virtual environment and then you can set up the project package.

```
python -m venv <venv-name>
pip install -e .
```

The second command must be run while in the project root directory (`vgc-matchup-predictor/`). Once you are done, re-run the above cell.

In [ ]:
# run this cell to import and process the datasets

import vgc_matchup_predictor.data.download_hf
import vgc_matchup_predictor.data.process_json

vgc_matchup_predictor.data.download_hf.download_hf_dataset()
vgc_matchup_predictor.data.process_json.start_process_data()

We'll start by importing the JSON files for the raw data using `pandas.read_json()`.

In [15]:
raw_ma = pd.read_json('../' + config['dataset']['raw_path'] + config['dataset']['m_a'])
raw_ma

,gen9championsvgc2026regma-2600664326,gen9championsvgc2026regma-2600407331,gen9championsvgc2026regma-2600687109,gen9championsvgc2026regma-2600573325,gen9championsvgc2026regma-2600148740,gen9championsvgc2026regma-2600076680,gen9championsvgc2026regma-2599901451,gen9championsvgc2026regma-2600289444,gen9championsvgc2026regma-2599798141,gen9championsvgc2026regma-2599790190,...,gen9championsvgc2026regma-2626640937,gen9championsvgc2026regma-2628783151,gen9championsvgc2026regma-2625565884,gen9championsvgc2026regma-2627117078,gen9championsvgc2026regma-2631487825,gen9championsvgc2026regma-2632061873,gen9championsvgc2026regma-2631930665,gen9championsvgc2026regma-2623115146,gen9championsvgc2026regma-2624138171,gen9championsvgc2026regma-2622688383
0,1777827111,1777794779,1777829212,1777818212,1777761794,1777754577,1777738827,1777777666,1777727787,1777728962,...,1780789986,1781054927,1780660888,1780855747,1781391517,1781471826,1781457213,1780375586,1780496941,1780327929
1,|j|☆skarmbag\n|j|☆kicks10\n|html|<table width=...,|j|☆magicalarcher57\n|j|☆Ekiller12z\n|t:|17777...,"|raw|<div class=""broadcast-blue""><strong>This ...",|j|☆magicalarcher57\n|j|☆mynamegrassgreen\n|t:...,|j|☆lowk like dat\n|j|☆anchor orchestra\n|t:|1...,|j|☆hiyopon\n|j|☆JonnyNerd\n|t:|1777754359\n|g...,|j|☆djogoclao\n|j|☆mynamegrassgreen\n|html|<ta...,|j|☆AtumAsar\n|j|☆magicalarcher57\n|html|<tabl...,|j|☆AragonVGC\n|j|☆goodbye brede\n|html|<table...,|j|☆treehuggingbunny\n|j|☆AragonVGC\n|html|<ta...,...,|j|☆MounreyVGC\n|j|☆Gabbs_win\n|html|<table wi...,|j|☆magicalarcher57\n|j|☆Omegateck\n|t:|178105...,|j|☆magicalarcher57\n|j|☆yasha1of1\n|html|<tab...,|j|☆toon b.d.g.\n|j|☆SoleilStellar\n|html|<tab...,|j|☆Prismatic Phantom\n|j|☆lolgz\n|t:|17813913...,|j|☆Jizao\n|j|☆Its Sushiii\n|t:|1781471413\n|g...,|j|☆Garbless\n|j|☆banana superior\n|t:|1781456...,|j|☆llamasnail\n|j|☆hp_45\n|t:|1780375015\n|ga...,|j|☆lolgz\n|j|☆niklasbvb1909\n|t:|1780496785\n...,|j|☆imapiglin\n|j|☆riku797vgc\n|html|<table wi...

In [17]:
raw_ma['gen9championsvgc2026regma-2600664326'][1]

'|j|☆skarmbag\n|j|☆kicks10\n|html|<table width="100%"><tr><td align="left">skarmbag</td><td align="right">kicks10</tr><tr><td align="left"><i class="fa fa-circle"></i> <i class="fa fa-circle-o"></i> </td><td align="right"><i class="fa fa-circle-o"></i> <i class="fa fa-circle"></i> </tr></table>\n|uhtml|bestof|<h2><strong>Game 3</strong> of <a href="/game-bestof3-gen9championsvgc2026regma-2600658778">a best-of-3</a></h2>\n|t:|1777826874\n|gametype|doubles\n|player|p1|skarmbag|irida|\n|player|p2|kicks10|flannery|\n|gen|9\n|tier|[Gen 9 Champions] VGC 2026 Reg M-A\n|rated|Tournament battle\n|rule|Species Clause: Limit one of each Pokémon\n|rule|Item Clause: Limit 1 of each item\n|raw|<div class="infobox"><details class="readmore" open><summary><strong>2 custom rules:</strong></summary> Force Open Team Sheets, Best of = 3</details></div>\n|clearpoke\n|poke|p1|Golurk, L50|\n|poke|p1|Torkoal, L50, M|\n|poke|p1|Farigiraf, L50, F|\n|poke|p1|Lucario, L50, M|\n|poke|p1|Aromatisse, L50, M|\n|poke|p1|Kangaskhan, L50, F|\n|poke|p2|Aerodactyl, L50, F|\n|poke|p2|Charizard, L50, F|\n|poke|p2|Floette-Eternal, L50, F|\n|poke|p2|Hydreigon, L50, F|\n|poke|p2|Garchomp, L50, F|\n|poke|p2|Rotom-Wash, L50|\n|teampreview|4\n|showteam|p1|Golurk||Golurkite|IronFist|Poltergeist,HeadlongRush,Protect,PhantomForce||||||50|]Torkoal||Charcoal|Drought|Eruption,HeatWave,Protect,EarthPower|||M|||50|]Farigiraf||SitrusBerry|ArmorTail|PsychicNoise,DazzlingGleam,HelpingHand,TrickRoom|||F|||50|]Lucario||ChoiceScarf|InnerFocus|FinalGambit,CloseCombat,IcePunch,Coaching|||M|||50|]Aromatisse||Leftovers|AromaVeil|DazzlingGleam,HealPulse,Protect,TrickRoom|||M|||50|]Kangaskhan||ChopleBerry|Scrappy|FakeOut,LastResort|||F|||50|\n|showteam|p2|Aerodactyl||FocusSash|Unnerve|Protect,Tailwind,RockSlide,WideGuard|||F|||50|]Charizard||CharizarditeY|SolarPower|Protect,HeatWave,WeatherBall,SolarBeam|||F|||50|]Floette-Eternal||Floettite|FlowerVeil|Protect,Moonblast,DazzlingGleam,LightofRuin|||F|||50|]Hydreigon||HabanBerry|Levitate|Protect,EarthPower,DarkPulse,DracoMeteor|||F|||50|]Garchomp||ChoiceScarf|RoughSkin|Earthquake,DragonClaw,RockSlide,IronHead|||F|||50|]Rotom-Wash||SitrusBerry|Levitate|Protect,VoltSwitch,WillOWisp,HydroPump||||||50|\n|inactive|Battle timer is ON: inactive players will automatically lose when time\'s up. (requested by skarmbag)\n|inactive|skarmbag has 60 seconds left.\n|inactive|kicks10 has 60 seconds left.\n|\n|t:|1777826914\n|teamsize|p1|4\n|teamsize|p2|4\n|start\n|switch|p1a: Aromatisse|Aromatisse, L50, M|100/100\n|switch|p1b: Lucario|Lucario, L50, M|100/100\n|switch|p2a: Charizard|Charizard, L50, F|100/100\n|switch|p2b: Hydreigon|Hydreigon, L50, F|100/100\n|turn|1\n|\n|t:|1777826930\n|move|p2a: Charizard|Protect|p2a: Charizard\n|-singleturn|p2a: Charizard|Protect\n|move|p1b: Lucario|Final Gambit|p2a: Charizard\n|-activate|p2a: Charizard|move: Protect\n|move|p2b: Hydreigon|Earth Power|p1b: Lucario\n|-supereffective|p1b: Lucario|1\n|-damage|p1b: Lucario|6/100\n|move|p1a: Aromatisse|Trick Room|p1a: Aromatisse\n|-fieldstart|move: Trick Room|[of] p1a: Aromatisse\n|\n|upkeep\n|turn|2\n|inactive|kicks10 has 30 seconds left.\n|inactive|kicks10 has 20 seconds left.\n|\n|t:|1777826969\n|switch|p1b: Kangaskhan|Kangaskhan, L50, F|100/100\n|detailschange|p2a: Charizard|Charizard-Mega-Y, L50, F\n|-mega|p2a: Charizard|Charizard|Charizardite Y\n|-weather|SunnyDay|[from] ability: Drought|[of] p2a: Charizard\n|move|p1a: Aromatisse|Protect|p1a: Aromatisse\n|-singleturn|p1a: Aromatisse|Protect\n|move|p2b: Hydreigon|Protect|p2b: Hydreigon\n|-singleturn|p2b: Hydreigon|Protect\n|move|p2a: Charizard|Weather Ball|p1a: Aromatisse\n|-activate|p1a: Aromatisse|move: Protect\n|\n|-weather|SunnyDay|[upkeep]\n|upkeep\n|turn|3\n|\n|t:|1777826987\n|switch|p2b: Garchomp|Garchomp, L50, F|100/100\n|move|p2a: Charizard|Protect|p2a: Charizard\n|-singleturn|p2a: Charizard|Protect\n|move|p1b: Kangaskhan|Fake Out|p2a: Charizard\n|-activate|p2a: Charizard|move: Protect\n|move|p1a: Aromatisse|Dazzling Gleam|p2b: Garchomp|[spread] p2b\n|-activate|p2a: Charizard|move: Protect\n|-supereffective|p2b: Garchomp|1\n|-damage|p2b: Garchomp|54/100\n|\n|-weather|SunnyDay|[upkeep]\n|upkeep\n|turn|4\n|\n|t:|1777827009\n|move|p1a: Aromatisse|Dazzling Gleam|p2b: Garchomp|[spread] p2a,p2b\n|-resisted|p2a: Charizard|1\n|-supereffective|p2b: Garchomp|1\n|-damage|p2a: Charizard|89/100\n|-damage|p2b: Garchomp|4/100\n|move|p1b: Kangaskhan|Last Resort|p2a: Charizard\n|-damage|p2a: Charizard|0 fnt\n|faint|p2a: Charizard\n|move|p2b: Garchomp|Earthquake|p1a: Aromatisse|[spread] p1a,p1b\n|-damage|p1a: Aromatisse|67/100\n|-damage|p1b: Kangaskhan|61/100\n|\n|-weather|SunnyDay|[upkeep]\n|-heal|p1a: Aromatisse|74/100|[from] item: Leftovers\n|upkeep\n|inactive|kicks10 has 30 seconds left.\n|\n|t:|1777827037\n|switch|p2a: Hydreigon|Hydreigon, L50, F|100/100\n|turn|5\n|\n|t:|1777827043\n|switch|p1b: Lucario|Lucario, L50, M|6/100\n|move|p2a: Hydreigon|Protect|p2a: Hydreigon\n|-singleturn|p2a: Hydreigon|Protect\n|move|p1a: Aromatisse|Dazzling Gleam|p2a: Hydreigon|[spread] p2b\n|-activate|p2a: Hydreigon|move: Protect\n|-supereffective|p2b: Garchomp|1\n|-damage|p2b: Garchomp|0 fnt\n|faint|p2b: Garchomp\n|\n|-weather|SunnyDay|[upkeep]\n|-heal|p1a: Aromatisse|80/100|[from] item: Leftovers\n|-fieldend|move: Trick Room\n|upkeep\n|\n|t:|1777827055\n|switch|p2b: Rotom|Rotom-Wash, L50|100/100\n|turn|6\n|inactive|kicks10 has 30 seconds left.\n|\n|t:|1777827080\n|move|p2a: Hydreigon|Protect||[still]\n|-fail|p2a: Hydreigon\n|move|p1a: Aromatisse|Protect|p1a: Aromatisse\n|-singleturn|p1a: Aromatisse|Protect\n|move|p1b: Lucario|Close Combat|p2b: Rotom\n|-damage|p2b: Rotom|51/100\n|-unboost|p1b: Lucario|def|1\n|-unboost|p1b: Lucario|spd|1\n|move|p2b: Rotom|Volt Switch|p1b: Lucario\n|-crit|p1b: Lucario\n|-damage|p1b: Lucario|0 fnt\n|faint|p1b: Lucario\n|\n|-weather|none\n|-heal|p1a: Aromatisse|86/100|[from] item: Leftovers\n|upkeep\n|\n|t:|1777827084\n|switch|p1b: Kangaskhan|Kangaskhan, L50, F|61/100\n|turn|7\n|-message|kicks10 forfeited.\n|\n|win|skarmbag\n|l|☆kicks10\n|player|p2|\n'

This data is not very visually friendly; there are 6905 different columns and only 3 rows, and the second row in each column seems to have a massive amount of data within it.

Intuitively, the second entry may look like some kind of log, and that is exactly what it is. Each entry in the dataframe is its own *Pokémon Showdown* battle, against two online players, and has a unique ID and the logs of the entire battle from beginning to end. There is far more data in these entries than we need for our models; we are only concerned with both players' team compositions and starting leads, not the entire outcome of the battle. `vgc_matchup_predictor.data.process_json.start_process_data()` deals with this by only saving what data is necessary and dumping it into a new, clean processed JSON file. This cuts a lot of garbage data out, for instance, the battle logs file for the Regulation M-A battles goes from a file size of ~50 MB to ~6.5 MB.

Let's take a look at the processed data for Reg. M-A.

In [18]:
processed_ma = pd.read_json('../' + config['dataset']['processed_path'] + config['dataset']['m_a'])
processed_ma

,battle_id,p1a,p1a item,p1a ability,p1a moves,p1a nature,p1b,p1b item,p1b ability,p1b moves,...,p2a item,p2a ability,p2a moves,p2a nature,p2b,p2b item,p2b ability,p2b moves,p2b nature,winner
0,gen9championsvgc2026regma-2600664326,Aromatisse,Leftovers,AromaVeil,"[DazzlingGleam, HealPulse, Protect, TrickRoom]",,Lucario,ChoiceScarf,InnerFocus,"[FinalGambit, CloseCombat, IcePunch, Coaching]",...,CharizarditeY,SolarPower,"[Protect, HeatWave, WeatherBall, SolarBeam]",,Hydreigon,HabanBerry,Levitate,"[Protect, EarthPower, DarkPulse, DracoMeteor]",,p1
1,gen9championsvgc2026regma-2600407331,Garchomp,SitrusBerry,RoughSkin,"[Protect, DragonClaw, Earthquake, RockSlide]",,Whimsicott,KebiaBerry,Prankster,"[Moonblast, Tailwind, Protect, Encore]",...,Leftovers,SandStream,"[RockSlide, StoneEdge, Crunch, Protect]",,Whimsicott,KebiaBerry,Prankster,"[Moonblast, Tailwind, Protect, Encore]",,p2
2,gen9championsvgc2026regma-2600687109,Pelipper,Leftovers,Drizzle,"[WeatherBall, Hurricane, WideGuard, Protect]",,Greninja,Greninjite,Protean,"[WeatherBall, IceBeam, DarkPulse, WaterShuriken]",...,FocusSash,Prankster,"[Moonblast, Encore, Tailwind, Protect]",,Typhlosion-Hisui,ChoiceScarf,Blaze,"[Eruption, HeatWave, ShadowBall, Overheat]",,p2
3,gen9championsvgc2026regma-2600573325,Whimsicott,KebiaBerry,Prankster,"[Moonblast, Tailwind, Protect, Encore]",,Glimmora,Glimmoranite,ToxicDebris,"[SpikyShield, PowerGem, SludgeBomb, EarthPower]",...,Gengarite,CursedBody,"[ShadowBall, SludgeBomb, PerishSong, Protect]",,Incineroar,ShucaBerry,Intimidate,"[FakeOut, FlareBlitz, Protect, PartingShot]",,p2
4,gen9championsvgc2026regma-2600148740,Meganium,Meganiumite,LeafGuard,"[SolarBeam, EarthPower, WeatherBall, Protect]",,Mamoswine,SoftSand,Oblivious,"[HighHorsepower, Protect, RockSlide, IceShard]",...,ChopleBerry,Intimidate,"[FlareBlitz, PartingShot, WillOWisp, FakeOut]",,Corviknight,Leftovers,MirrorArmor,"[BraveBird, Tailwind, BulkUp, Roost]",,p1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6900,gen9championsvgc2026regma-2632061873,Pelipper,FocusSash,Drizzle,"[Hurricane, Tailwind, WeatherBall, Protect]",Modest,Incineroar,ChopleBerry,Intimidate,"[FakeOut, FlareBlitz, Protect, PartingShot]",...,FocusSash,SandRush,"[IronHead, HighHorsepower, RockSlide, Protect]",Jolly,Tyranitar,Tyranitarite,SandStream,"[RockSlide, KnockOff, IcePunch, Protect]",Adamant,p1
6901,gen9championsvgc2026regma-2631930665,Drampa,Drampanite,CloudNine,"[HyperVoice, HeatWave, DragonPulse, Protect]",Quiet,Farigiraf,MentalHerb,ArmorTail,"[HyperVoice, TrickRoom, TwinBeam, HelpingHand]",...,Altarianite,CloudNine,"[HyperVoice, Tailwind, Protect, PerishSong]",Modest,Incineroar,SitrusBerry,Intimidate,"[PartingShot, ThroatChop, FlareBlitz, FakeOut]",Adamant,p2
6902,gen9championsvgc2026regma-2623115146,Delphox,Delphoxite,Blaze,"[HeatWave, Protect, Encore, Psyshock]",Timid,Sinistcha,ColburBerry,Hospitality,"[MatchaGotcha, RagePowder, LifeDew, TrickRoom]",...,ChoiceScarf,Adaptability,"[AquaJet, LastRespects, WaveCrash, FlipTurn]",Adamant,Pelipper,FocusSash,Drizzle,"[Protect, Tailwind, Hurricane, WeatherBall]",Timid,p1
6903,gen9championsvgc2026regma-2624138171,Medicham,FocusSash,PurePower,"[CloseCombat, FakeOut, ZenHeadbutt, ThunderPunch]",Brave,Farigiraf,ColburBerry,ArmorTail,"[Psychic, Protect, TrickRoom, HelpingHand]",...,Scizorite,Technician,"[DualWingbeat, BulletPunch, BatonPass, SwordsD...",Naive,Krookodile,QuickClaw,Intimidate,"[BrickBreak, Earthquake, ThroatChop, Fissure]",Naive,p1
6904,gen9championsvgc2026regma-2622688383,Delphox,Delphoxite,Blaze,"[HeatWave, Psychic, Protect, NastyPlot]",Timid,Clefable,Leftovers,MagicGuard,"[Moonblast, FollowMe, Protect, ThunderWave]",...,Gardevoirite,Telepathy,"[TrickRoom, Protect, HyperVoice, Psychic]",Modest,Incineroar,ShucaBerry,Intimidate,"[FakeOut, HelpingHand, PartingShot, FlareBlitz]",Impish,p2

Now we have a much more digestible and ready-to-use table.